spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: com.springboot.project.common.database.CustomH2Dialect
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          "[time_zone]": UTC
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  liquibase:
    enabled: false
    change-log: classpath:liquibase/index.xml
  h2:
    console:
      enabled: false
  mail:
    host: smtp.163.com
    username: zdu_20230408001@163.com
    password: INCFTHKUALEWKKTK
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  task:
    scheduling:
      pool:
        size: 50
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    write-dates-as-timestamps: false
    time-zone: UTC
logging:
  level:
    org:
      hibernate:
        dialect:
          function:
            TemplateRenderer: ERROR
        SQL: OFF
        orm:
          jdbc:
            bind: OFF
server:
  error:
    include-message: always
  tomcat:
    max-http-form-post-size: -1
  max-http-header-size: 40KB
properties:
  storage:
    root:
      path: ${storage.root.path}
    cloud:
      aliyun:
        enabled: ${storage.cloud.aliyun.enabled}
        endpoint: ${storage.cloud.aliyun.endpoint}
        bucketName: ${storage.cloud.aliyun.bucketName}
        accessKeyId: ${storage.cloud.aliyun.accessKeyId}
        accessKeySecret: ${storage.cloud.aliyun.accessKeySecret}
