spring:
  datasource:
    url: jdbc:mysql://${database.mysql.jdbc.url}/${database.mysql.name}?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${database.mysql.username}
    password: ${database.mysql.password}
    driver-class-name: ${database.mysql.driver}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: ${database.mysql.platform}
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          "[time_zone]": UTC
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  liquibase:
    enabled: true
    change-log: classpath:liquibase/index.xml
  h2:
    console:
      enabled: false
  mail:
    host: smtp.163.com
    username: zdu_20230408001@163.com
    password: INCFTHKUALEWKKTK
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  task:
    scheduling:
      pool:
        size: 1000
logging:
  level:
    org:
      hibernate:
        dialect:
          function:
            TemplateRenderer: ERROR
        SQL: OFF
        orm:
          jdbc:
            bind: OFF
server:
  error:
    include-message: always
  tomcat:
    max-http-form-post-size: -1
properties:
  StorageRootPath: ${StorageRootPath}
